import { Question } from '@/types';

export const sampleQuestions: Question[] = [
  // 政治 - 马克思主义原理
  {
    id: 'politics-1',
    subjectId: 'politics',
    chapterId: 'politics-materialism',
    content: '马克思主义哲学认为，世界的本质是：',
    options: ['A. 物质', 'B. 意识', 'C. 精神', 'D. 实践'],
    answer: 0,
    explanation: '马克思主义哲学是唯物主义哲学，认为世界的本质是物质，物质决定意识。',
  },
  {
    id: 'politics-2',
    subjectId: 'politics',
    chapterId: 'politics-materialism',
    content: '哲学的基本问题是：',
    options: ['A. 唯物主义和唯心主义的关系', 'B. 物质和意识的关系', 'C. 辩证法和形而上学的关系', 'D. 理论和实践的关系'],
    answer: 1,
    explanation: '哲学的基本问题是思维和存在的关系问题，也就是意识和物质的关系问题。',
  },
  {
    id: 'politics-3',
    subjectId: 'politics',
    chapterId: 'politics-dialectics',
    content: '唯物辩证法的实质和核心是：',
    options: ['A. 质量互变规律', 'B. 否定之否定规律', 'C. 对立统一规律', 'D. 因果规律'],
    answer: 2,
    explanation: '对立统一规律是唯物辩证法的实质和核心，它揭示了事物发展的源泉和动力。',
  },
  {
    id: 'politics-4',
    subjectId: 'politics',
    chapterId: 'politics-dialectics',
    content: '"白马非马"的命题，其错误在于：',
    options: ['A. 割裂了矛盾的普遍性和特殊性的关系', 'B. 割裂了内因和外因的关系', 'C. 割裂了量变和质变的关系', 'D. 割裂了肯定和否定的关系'],
    answer: 0,
    explanation: '"白马非马"割裂了矛盾的普遍性（马）和特殊性（白马）的辩证关系。',
  },
  {
    id: 'politics-5',
    subjectId: 'politics',
    chapterId: 'politics-epistemology',
    content: '实践是检验真理的唯一标准，这是因为：',
    options: ['A. 实践是认识的来源', 'B. 实践是认识发展的动力', 'C. 实践具有直接现实性的特点', 'D. 实践是认识的目的'],
    answer: 2,
    explanation: '实践之所以是检验真理的唯一标准，是由真理的本性和实践的特点决定的，实践具有直接现实性的特点。',
  },
  {
    id: 'politics-6',
    subjectId: 'politics',
    chapterId: 'politics-epistemology',
    content: '感性认识的形式不包括：',
    options: ['A. 感觉', 'B. 知觉', 'C. 表象', 'D. 概念'],
    answer: 3,
    explanation: '感性认识的形式包括感觉、知觉和表象。概念是理性认识的形式。',
  },
  {
    id: 'politics-7',
    subjectId: 'politics',
    chapterId: 'politics-historical-materialism',
    content: '社会存在是指：',
    options: ['A. 社会生活的精神方面', 'B. 社会物质生活条件的总和', 'C. 社会的政治制度', 'D. 社会的意识形态'],
    answer: 1,
    explanation: '社会存在是指社会物质生活条件的总和，包括地理环境、人口因素和物质资料的生产方式。',
  },
  {
    id: 'politics-8',
    subjectId: 'politics',
    chapterId: 'politics-historical-materialism',
    content: '生产力中最活跃的因素是：',
    options: ['A. 劳动资料', 'B. 劳动对象', 'C. 劳动者', 'D. 科学技术'],
    answer: 2,
    explanation: '劳动者是生产力中最活跃的因素，在生产中起主导作用。',
  },

  // 英语 - 词汇
  {
    id: 'english-1',
    subjectId: 'english',
    chapterId: 'english-vocabulary',
    content: 'The company has decided to ________ its business to include software development.',
    options: ['A. expand', 'B. extend', 'C. enlarge', 'D. multiply'],
    answer: 0,
    explanation: 'expand 指范围、体积、数量等的扩大；extend 指时间或空间的延伸；enlarge 指尺寸或体积的增大；multiply 指数量的倍增。此处指业务范围的扩大，用 expand。',
  },
  {
    id: 'english-2',
    subjectId: 'english',
    chapterId: 'english-vocabulary',
    content: 'She was so ________ in her work that she didn\'t hear the phone ring.',
    options: ['A. attracted', 'B. drawn', 'C. concentrated', 'D. absorbed'],
    answer: 3,
    explanation: 'be absorbed in 是固定搭配，意为"全神贯注于"。',
  },
  {
    id: 'english-3',
    subjectId: 'english',
    chapterId: 'english-reading',
    content: 'Which of the following best summarizes the main idea of the passage?',
    options: ['A. Technology has both positive and negative effects.', 'B. Technology is always beneficial.', 'C. Technology should be avoided.', 'D. Technology is neutral.'],
    answer: 0,
    explanation: '文章的主旨通常是综合性的，既承认技术的积极影响，也指出其消极影响，而非极端观点。',
  },
  {
    id: 'english-4',
    subjectId: 'english',
    chapterId: 'english-reading',
    content: 'The word "it" in line 3 refers to ________.',
    options: ['A. the previous noun', 'B. the following noun', 'C. a general concept', 'D. the main subject'],
    answer: 0,
    explanation: '代词通常指代前面提到的名词，这是阅读理解中的常见考点。',
  },
  {
    id: 'english-5',
    subjectId: 'english',
    chapterId: 'english-writing',
    content: 'Which transition word is best used to show contrast?',
    options: ['A. Furthermore', 'B. However', 'C. Therefore', 'D. Similarly'],
    answer: 1,
    explanation: 'However 表示转折/对比；Furthermore 表示递进；Therefore 表示因果；Similarly 表示相似。',
  },
  {
    id: 'english-6',
    subjectId: 'english',
    chapterId: 'english-writing',
    content: 'In academic writing, which is the most appropriate way to express opinion?',
    options: ['A. I think...', 'B. It is widely believed that...', 'C. You know...', 'D. Everybody says...'],
    answer: 1,
    explanation: '学术写作应使用客观、正式的表达方式，避免使用第一人称和口语化表达。',
  },
  {
    id: 'english-7',
    subjectId: 'english',
    chapterId: 'english-translation',
    content: 'Translate: "他不仅聪明，而且勤奋。" Which structure is correct?',
    options: ['A. He is not only clever but also diligent.', 'B. He is clever and also diligent.', 'C. He is both clever and diligent.', 'D. He is as clever as diligent.'],
    answer: 0,
    explanation: 'not only...but also... 是"不仅...而且..."的标准翻译结构。',
  },
  {
    id: 'english-8',
    subjectId: 'english',
    chapterId: 'english-cloze',
    content: 'In the sentence "The book _____ on the table is mine," which word best fills the blank?',
    options: ['A. laying', 'B. lying', 'C. laid', 'D. lain'],
    answer: 1,
    explanation: 'lying 是 lie（躺）的现在分词形式，此处作后置定语。laying 是 lay（放置）的现在分词。',
  },

  // 数学 - 高等数学
  {
    id: 'math-1',
    subjectId: 'math',
    chapterId: 'math-limit',
    content: 'lim(x→0) sin(x)/x = ?',
    options: ['A. 0', 'B. 1', 'C. ∞', 'D. 不存在'],
    answer: 1,
    explanation: '这是重要极限之一，lim(x→0) sin(x)/x = 1。',
  },
  {
    id: 'math-2',
    subjectId: 'math',
    chapterId: 'math-limit',
    content: '函数 f(x) = 1/x 在 x = 0 处：',
    options: ['A. 有极限', 'B. 连续', 'C. 可导', 'D. 无定义'],
    answer: 3,
    explanation: '函数 f(x) = 1/x 在 x = 0 处无定义，因此在该点不连续、不可导、无极限。',
  },
  {
    id: 'math-3',
    subjectId: 'math',
    chapterId: 'math-derivative',
    content: '若 f(x) = x²，则 f\'(x) = ?',
    options: ['A. x', 'B. 2x', 'C. x²', 'D. 2x²'],
    answer: 1,
    explanation: '根据幂函数求导公式，(xⁿ)\' = nxⁿ⁻¹，所以 (x²)\' = 2x。',
  },
  {
    id: 'math-4',
    subjectId: 'math',
    chapterId: 'math-derivative',
    content: '函数 f(x) = eˣ 的导数是：',
    options: ['A. eˣ', 'B. xeˣ⁻¹', 'C. eˣ⁻¹', 'D. ln(x)'],
    answer: 0,
    explanation: 'eˣ 的导数仍然是 eˣ，这是指数函数的特殊性质。',
  },
  {
    id: 'math-5',
    subjectId: 'math',
    chapterId: 'math-integral',
    content: '∫ 2x dx = ?',
    options: ['A. x²', 'B. x² + C', 'C. 2', 'D. 2x²'],
    answer: 1,
    explanation: '不定积分的结果需要加上任意常数 C。∫ 2x dx = x² + C。',
  },
  {
    id: 'math-6',
    subjectId: 'math',
    chapterId: 'math-integral',
    content: '定积分 ∫₀¹ x² dx = ?',
    options: ['A. 1/2', 'B. 1/3', 'C. 1/4', 'D. 1'],
    answer: 1,
    explanation: '∫₀¹ x² dx = [x³/3]₀¹ = 1/3 - 0 = 1/3。',
  },
  {
    id: 'math-7',
    subjectId: 'math',
    chapterId: 'math-multi-derivative',
    content: '二元函数 z = x² + y² 的偏导数 ∂z/∂x = ?',
    options: ['A. 2x', 'B. 2y', 'C. 2x + 2y', 'D. x²'],
    answer: 0,
    explanation: '对 x 求偏导时，将 y 视为常数，所以 ∂z/∂x = 2x。',
  },
  {
    id: 'math-8',
    subjectId: 'math',
    chapterId: 'math-ode',
    content: '微分方程 y\' = 2x 的通解是：',
    options: ['A. y = x²', 'B. y = x² + C', 'C. y = 2x²', 'D. y = 2x + C'],
    answer: 1,
    explanation: '对 y\' = 2x 两边积分，得 y = x² + C，其中 C 为任意常数。',
  },

  // 数学 - 线性代数
  {
    id: 'math-9',
    subjectId: 'math',
    chapterId: 'math-matrix',
    content: '单位矩阵的行列式值为：',
    options: ['A. 0', 'B. 1', 'C. -1', 'D. n'],
    answer: 1,
    explanation: '单位矩阵的对角线元素全为 1，其余为 0，其行列式值为 1。',
  },
  {
    id: 'math-10',
    subjectId: 'math',
    chapterId: 'math-determinant',
    content: '若 A 是 3 阶方阵，且 |A| = 2，则 |2A| = ?',
    options: ['A. 4', 'B. 8', 'C. 16', 'D. 6'],
    answer: 2,
    explanation: '|kA| = kⁿ|A|，其中 n 是矩阵的阶数。所以 |2A| = 2³ × 2 = 16。',
  },
  {
    id: 'math-11',
    subjectId: 'math',
    chapterId: 'math-vector',
    content: '向量组 α₁ = (1,0,0), α₂ = (0,1,0), α₃ = (0,0,1) 的秩为：',
    options: ['A. 0', 'B. 1', 'C. 2', 'D. 3'],
    answer: 3,
    explanation: '这三个向量线性无关，构成三维空间的一组基，所以秩为 3。',
  },
  {
    id: 'math-12',
    subjectId: 'math',
    chapterId: 'math-equation',
    content: '齐次线性方程组 Ax = 0 有非零解的充要条件是：',
    options: ['A. |A| = 0', 'B. |A| ≠ 0', 'C. A = 0', 'D. A ≠ 0'],
    answer: 0,
    explanation: '齐次线性方程组有非零解的充要条件是系数矩阵的行列式等于 0，即 |A| = 0。',
  },
  {
    id: 'math-13',
    subjectId: 'math',
    chapterId: 'math-eigenvalue',
    content: '矩阵 A 的特征值之和等于：',
    options: ['A. |A|', 'B. tr(A)', 'C. A²', 'D. A⁻¹'],
    answer: 1,
    explanation: '矩阵 A 的特征值之和等于 A 的迹 tr(A)，即对角线元素之和。',
  },
  {
    id: 'math-14',
    subjectId: 'math',
    chapterId: 'math-quadratic',
    content: '二次型 f = x² + 2y² + 3z² 是：',
    options: ['A. 正定', 'B. 负定', 'C. 半正定', 'D. 不定'],
    answer: 0,
    explanation: '该二次型的系数全为正，且没有交叉项，所以是正定二次型。',
  },

  // 数学 - 概率论
  {
    id: 'math-15',
    subjectId: 'math',
    chapterId: 'math-event',
    content: '掷一枚均匀硬币，出现正面的概率是：',
    options: ['A. 0', 'B. 0.5', 'C. 1', 'D. 不确定'],
    answer: 1,
    explanation: '均匀硬币出现正面和反面是等可能事件，概率各为 0.5。',
  },
  {
    id: 'math-16',
    subjectId: 'math',
    chapterId: 'math-random-variable',
    content: '离散型随机变量 X 的分布律必须满足：',
    options: ['A. P(X=xᵢ) ≥ 0', 'B. ΣP(X=xᵢ) = 1', 'C. P(X=xᵢ) ≤ 1', 'D. 以上都对'],
    answer: 3,
    explanation: '分布律必须满足非负性（A）和归一性（B），且每个概率值不超过 1（C）。',
  },
  {
    id: 'math-17',
    subjectId: 'math',
    chapterId: 'math-expectation',
    content: '若 X ~ N(0,1)，则 E(X) = ?',
    options: ['A. -1', 'B. 0', 'C. 1', 'D. 2'],
    answer: 1,
    explanation: '标准正态分布 N(0,1) 的期望 E(X) = 0。',
  },
  {
    id: 'math-18',
    subjectId: 'math',
    chapterId: 'math-expectation',
    content: '若 X ~ B(n,p)，则 D(X) = ?',
    options: ['A. np', 'B. np(1-p)', 'C. n(1-p)', 'D. p(1-p)'],
    answer: 1,
    explanation: '二项分布 B(n,p) 的方差 D(X) = np(1-p)。',
  },
  {
    id: 'math-19',
    subjectId: 'math',
    chapterId: 'math-law-large',
    content: '大数定律表明，当 n→∞ 时，样本均值依概率收敛于：',
    options: ['A. 0', 'B. 1', 'C. 总体均值 μ', 'D. 样本方差'],
    answer: 2,
    explanation: '大数定律表明，样本均值依概率收敛于总体均值 μ。',
  },
  {
    id: 'math-20',
    subjectId: 'math',
    chapterId: 'math-statistics',
    content: '在假设检验中，犯第一类错误的概率记为：',
    options: ['A. α', 'B. β', 'C. 1-α', 'D. 1-β'],
    answer: 0,
    explanation: '第一类错误（弃真错误）的概率记为 α，第二类错误（取伪错误）的概率记为 β。',
  },

  // 专业课 - 数据结构
  {
    id: 'professional-1',
    subjectId: 'professional',
    chapterId: 'professional-ds',
    content: '栈的特点是：',
    options: ['A. 先进先出', 'B. 后进先出', 'C. 随机访问', 'D. 以上都不是'],
    answer: 1,
    explanation: '栈是一种后进先出（LIFO）的数据结构，最后入栈的元素最先出栈。',
  },
  {
    id: 'professional-2',
    subjectId: 'professional',
    chapterId: 'professional-ds',
    content: '队列的特点是：',
    options: ['A. 先进先出', 'B. 后进先出', 'C. 随机访问', 'D. 以上都不是'],
    answer: 0,
    explanation: '队列是一种先进先出（FIFO）的数据结构，最先入队的元素最先出队。',
  },
  {
    id: 'professional-3',
    subjectId: 'professional',
    chapterId: 'professional-ds',
    content: '二叉树的前序遍历顺序是：',
    options: ['A. 左-根-右', 'B. 根-左-右', 'C. 左-右-根', 'D. 右-根-左'],
    answer: 1,
    explanation: '二叉树的前序遍历顺序是：根节点-左子树-右子树。',
  },
  {
    id: 'professional-4',
    subjectId: 'professional',
    chapterId: 'professional-algo',
    content: '快速排序的平均时间复杂度是：',
    options: ['A. O(n)', 'B. O(n log n)', 'C. O(n²)', 'D. O(log n)'],
    answer: 1,
    explanation: '快速排序的平均时间复杂度是 O(n log n)，最坏情况是 O(n²)。',
  },
  {
    id: 'professional-5',
    subjectId: 'professional',
    chapterId: 'professional-algo',
    content: '下列排序算法中，稳定性最好的是：',
    options: ['A. 快速排序', 'B. 归并排序', 'C. 堆排序', 'D. 选择排序'],
    answer: 1,
    explanation: '归并排序是稳定的排序算法，而快速排序、堆排序和选择排序都是不稳定的。',
  },
  {
    id: 'professional-6',
    subjectId: 'professional',
    chapterId: 'professional-network',
    content: 'OSI 参考模型共有几层？',
    options: ['A. 4 层', 'B. 5 层', 'C. 6 层', 'D. 7 层'],
    answer: 3,
    explanation: 'OSI 参考模型将网络通信分为 7 层：物理层、数据链路层、网络层、传输层、会话层、表示层、应用层。',
  },
  {
    id: 'professional-7',
    subjectId: 'professional',
    chapterId: 'professional-network',
    content: 'TCP 协议工作在 OSI 模型的哪一层？',
    options: ['A. 网络层', 'B. 传输层', 'C. 会话层', 'D. 应用层'],
    answer: 1,
    explanation: 'TCP（传输控制协议）工作在传输层，提供可靠的端到端通信。',
  },
  {
    id: 'professional-8',
    subjectId: 'professional',
    chapterId: 'professional-os',
    content: '进程和程序的根本区别是：',
    options: ['A. 是否占用内存', 'B. 是否有状态', 'C. 是否可并发执行', 'D. 以上都是'],
    answer: 3,
    explanation: '进程是程序的一次执行，具有动态性、并发性、独立性等特点，与程序的根本区别包括以上所有方面。',
  },
];

export function getQuestionsBySubject(subjectId: string): Question[] {
  return sampleQuestions.filter((q) => q.subjectId === subjectId);
}

export function getQuestionsByChapter(chapterId: string): Question[] {
  return sampleQuestions.filter((q) => q.chapterId === chapterId);
}
